# Generated by Django 2.2.6 on 2019-11-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('month', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Fires',
                'managed': False,
            },
        ),
    ]
